spring.application.name=student_attendance

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=attendance_user
spring.datasource.password=attendance_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
